config/routes.rb
Rails.application.routes.draw do
  resources :fighters, path: '/combattants', except: []
  resources :fights, path: '/combats', only: [:index, :show, :new, :create]

  root to: 'home#home'
end

app/models/fighter.rb
# frozen_string_literal: true.
##
# Fighter is the app central model.
# @since v0
#
class Fighter < ApplicationRecord
  MAX_TOTAL_BASE_POINTS = ENV['MAX_TOTAL_BASE_POINTS'].to_i
  MAX_DEFENSE_BASE_POINTS = ENV['MAX_DEFENSE_BASE_POINTS'].to_i
  MAX_HEALTH_BASE_POINTS = ENV['MAX_HEALTH_BASE_POINTS'].to_i

  has_many :won_fights, class_name: :Fight, foreign_key: :winner_id

  validates :name, presence: true

  validates :attack_base_points,
    presence: true,
    numericality: { only_integer: true }
  validates :defense_base_points,
    presence: true,
    numericality: {
      less_than_or_equal_to: MAX_DEFENSE_BASE_POINTS,
      only_integer: true
    }
  validates :health_base_points,
    presence: true,
    numericality: {
      less_than_or_equal_to: MAX_HEALTH_BASE_POINTS,
      only_integer: true
    }
  validates :color_code, presence: true, length: { is: 6 }
  validates_format_of :color_code, with: /\A[0-9a-fA-F]{6}\z/

  validate :has_valid_base_points?

  after_initialize :set_default_base_points
  after_initialize :set_default_color

  attr_accessor :current_health

  # String version of the instance (using +name+ & +id+).
  # @return [String]
  #
  def to_s
    "#{name} [#{id}]"
  end

  # The total amount of base points (distributed between +attack_base_points+, +defense_base_points+ & +health_base_points+)
  # @return [Integer]
  # @see attack_base_points
  # @see defense_base_points
  # @see health_base_points
  #
  def total_base_points
    attack_base_points.to_i + defense_base_points.to_i + health_base_points.to_i
  end

  # The maximum health points (calculated with +total_base_points+, +defense_base_points+ & +health_base_points+)
  # @return [Integer]
  # @see total_base_points
  # @see defense_base_points
  # @see health_base_points
  #
  def max_health
    (total_base_points + defense_base_points.to_i + health_base_points.to_i*2)*10
  end


  # Compute the damages of a hit blown to a different Fighter (partially randomized)
  # @return [Integer]
  # @see attack_base_points
  # @see defense_base_points
  #
  def hit(opponent)
    raise 'Cannot hit himself' if self == opponent

    theoretical_damages = self.attack_base_points - opponent.defense_base_points
    real_damages = rand((theoretical_damages/2)..(theoretical_damages*2))

    return opponent.current_health > real_damages ? real_damages : opponent.current_health
  end

  private

  # Validation that +total_base_points+ is not above Fighter::MAX_TOTAL_BASE_POINTS
  # @return [Boolean]
  # @see total_base_points
  #
  def has_valid_base_points?
    if total_base_points > MAX_TOTAL_BASE_POINTS
      error_label = I18n.t('activerecord.errors.models.fighter.attack_base_points.total_base_points_must_be_below', max_value: MAX_TOTAL_BASE_POINTS)
      errors.add(:attack_base_points, error_label)
      return false
    end
    return true
  end

  # Set all undefined *_base_points attributes value to 0.
  #
  def set_default_base_points
    self.attack_base_points ||= 0
    self.defense_base_points ||= 0
    self.health_base_points ||= 0
    self.current_health = self.max_health
  end

  # Set a default value for color_code.
  #
  def set_default_color
    self.color_code ||= SecureRandom.hex(3)
  end
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  before_action :set_fighter, only: [:show, :edit, :update, :destroy]

  # GET /fighters
  def index
    @pagy, @fighters = pagy(Fighter.all)
  end

  # GET /fighters/1
  def show
    @won_fights = @fighter.won_fights
  end

  # GET /fighters/new
  def new
    @fighter = Fighter.new
  end

  # GET /fighters/1/edit
  def edit
  end

  # POST /fighters
  def create
    @fighter = Fighter.new(fighter_params)

    respond_to do |format|
      if @fighter.save
        format.html {
          redirect_to [@fighter],
          notice: t(
            'shared.notice.successful_creation',
            klass: Fighter.model_name.human.humanize,
            instance: @fighter
          )
        }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /fighters/1
  def update
    respond_to do |format|
      if @fighter.update(fighter_params)
        format.html {
          redirect_to [@fighter],
          notice: t(
            'shared.notice.successful_update',
            klass: Fighter.model_name.human.humanize,
            instance: @fighter
          )
        }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /fighters/1
  def destroy
    @fighter.destroy
    respond_to do |format|
      format.html {
        redirect_to admin_fighters_url,
        notice: t(
          'shared.notice.successful_destruction',
          klass: Fighter.model_name.human.humanize,
          instance: @fighter
        )
      }
    end
  end

  private
    def set_fighter
      @fighter = Fighter.find(params[:id])
    end

    def fighter_attrs
      [
        :name,
        :attack_base_points,
        :defense_base_points,
        :health_base_points,
        :color_code
      ]
    end

    def fighter_params
      params.require(:fighter).permit(fighter_attrs)
    end

end

app/views/fighters/_fields.html.haml
.row
  .col-12
    .form-group
      = form.input :name

  .col-12.col-sm-4
    .form-group
      = form.input :attack_base_points

  .col-12.col-sm-4
    .form-group
      = form.input :defense_base_points

  .col-12.col-sm-4
    .form-group
      = form.input :health_base_points

app/views/fighters/_form.html.haml
.card.col-12
  .card-body
    = simple_form_for([fighter]) do |f|
      = render 'fields', form: f

      .row
        .col-12.text-center
          = f.button :submit, t('shared.action.save'), class: 'btn btn-success'

app/views/fighters/_list.html.haml
.card

  .card-header
    %h2= Fighter.model_name.human.pluralize.humanize

  .card-body
    .row

      .col-12
        .table-responsive-sm

          %table.table.table-hover.table-sm.align-middle
            %thead.thead-dark.text-center
              %tr
                %th{ scope: 'col' }= t('activerecord.attributes.fighter.id').humanize
                %th{ scope: 'col' }= t('activerecord.attributes.fighter.name').humanize
                %th
                  = link_to new_fighter_path, class: 'btn btn-success' do
                    %i.fas.fa-fw.fa-plus

            %tbody
              - fighters.each do |fighter|
                %tr
                  %th.text-center{ scope: 'row' }= fighter.id
                  %td= fighter.name
                  %td.text-center
                    = link_to fighter_path(fighter), class: 'btn btn-sm btn-info', title: t('shared.action.show') do
                      %i.fas.fa-fw.fa-eye
                    = link_to edit_fighter_path(fighter), class: 'btn btn-sm btn-warning', title: t('shared.action.update') do
                      %i.fas.fa-fw.fa-edit

      - if local_assigns[:pagy]
        .col-12.justify-content-center!= pagy_bootstrap_nav(pagy)

app/views/fighters/edit.html.haml
= render 'form', fighter: @fighter

app/views/fighters/index.html.haml
= render 'list', fighters: @fighters, pagy: @pagy

app/views/fighters/new.html.haml
= render 'form', fighter: @fighter

app/views/fighters/show.html.haml
.card
  .card-header
    %h2= @fighter

  .card-body
    .row
      .col-12.col-sm-6
        %ul.list-group
          - %w(id name).each do |attribute|
            %li.list-group-item
              %h6= t("activerecord.attributes.fighter.#{attribute}").humanize
              %span= @fighter.send(attribute)

          %li.list-group-item.text-center
            %i.fas.fa-vial.h1{ style: "color: ##{@fighter.color_code}" }

      .col-12.col-sm-6
        %ul.list-group
          - %w(total_base_points attack_base_points defense_base_points health_base_points xp).each do |attribute|
            %li.list-group-item
              %h6= t("activerecord.attributes.fighter.#{attribute}").humanize
              %span= @fighter.send(attribute)

      - unless @won_fights.empty?
        .col-12
          %hr

        .col-12
          = render 'fights/list', fights: @won_fights, hide_new: true, title: t('activerecord.attributes.fighter.won_fights').humanize