config/routes.rb
Rails.application.routes.draw do
  resources :fighters, path: '/combattants', except: []
  resources :fights, path: '/combats', only: [:index, :show, :new, :create]

  root to: 'home#home'
end

app/views/shared/_alert.html.haml
.alert.alert-dismissible.fade.show.text-center{ role: :alert, class: "alert-#{type}" }
  = message.humanize
  %button.close{ type: :button, data: { dismiss: :alert } }
    %span{ aria: { hidden: true } }
      &times;

app/views/shared/_alerts.html.haml
- notices = notices.values.flatten.compact.uniq if notices.is_a?(Hash)
- notices = [notices].flatten.compact.uniq if !notices.is_a?(Enumerable)
- warnings = warnings.values.flatten.compact.uniq if warnings.is_a?(Hash)
- warnings = [warnings].flatten.compact.uniq if !warnings.is_a?(Enumerable)

.row
  .col-10.offset-xs-1.col-sm-6.offset-sm-3

    - notices.each do |message|
      = render '/shared/alert', message: message, type: :info

    - warnings.each do |message|
      = render '/shared/alert', message: message, type: :warning

app/views/shared/_header.html.haml
%header.mb-5
  %nav.navbar.navbar-expand-md.navbar-dark.bg-dark
    .container
      = link_to root_url, { class: 'navbar-brand' } do
        %i.fas.fa-vials
        %strong= t('shared.header.title')
      %button.navbar-toggler{ data: { toggle: :collapse, taget: '#main-nav' }, aria: { controls: 'main-nav', expanded: false } }
        %span.navbar-toggler-icon

      .collapse.navbar-collapse#main-nav
        = render 'shared/nav'

app/views/shared/_nav.html.haml
- fighters_class = %w(fighters).include?(params['controller']) ? 'active' : ''
- fights_class = %w(fights).include?(params['controller']) ? 'active' : ''

%ul.nav.navbar-nav
  %li.nav-item
    = link_to fighters_path, { class: "nav-link #{fighters_class}" } do
      %i.fas.fa-vial
      = Fighter.model_name.human.pluralize.humanize

  %li.nav-item
    = link_to fights_path, { class: "nav-link #{fights_class}" } do
      %i.fas.fa-vials
      = Fight.model_name.human.pluralize.humanize