config/routes.rb
Rails.application.routes.draw do
  resources :fighters, path: '/combattants', except: []
  resources :fights, path: '/combats', only: [:index, :show, :new, :create]

  root to: 'home#home'
end

app/models/fight.rb
# frozen_string_literal: true.
##
# Fight is the interraction model between Fighters.
# @since v3
#
class Fight < ApplicationRecord
  belongs_to :fighter_a, class_name: :Fighter
  belongs_to :fighter_b, class_name: :Fighter

  belongs_to :winner, class_name: :Fighter, optional: true

  validate :has_two_different_opponents?

  after_create :distribute_xp!
  before_create :start!

  before_save :set_title

  # String version of the instance (using +name+ & +id+).
  # @return [String]
  #
  def to_s
    "##{id} - #{fighter_a} VS #{fighter_b}"
  end

  # Start the Fight process if the Fighters are defined, and if it has not started already
  # @return [Fight or Boolean]
  #
  def start!
    return self.errors.messages unless self.valid?
    unless hits.nil? || hits.empty?
      return false && raise(StandardError, 'Cannot restart a fight')
    end

    self.hits = []

    fighters = [fighter_a, fighter_b].shuffle
    hit_until_death(fighters.first, fighters.last)
  end

  private

  # Recursive function to determine a winner of a Fight
  # @return [Fight]
  #
  def hit_until_death(attacker, defender)
    damages = attacker.hit(defender)
    defender.current_health -= attacker.hit(defender)

    self.hits << {
      attacker_id: attacker.id,
      defender_id: defender.id,
      damages: damages
    }

    if defender.current_health == 0
      self.winner = attacker
      set_xp_gain(defender)
      return self.winner
    else
      hit_until_death(defender, attacker)
    end
  end

  # Compute xp from a fight
  # @return [Integer]
  #
  def set_xp_gain(looser)
    return unless self.winner
    self.xp_gain = (looser.xp + looser.total_base_points)/10
  end

  # Update the +winner+ xp resulting from a Fight
  # @return [Boolean]
  #
  def distribute_xp!
    return false unless self.winner
    set_xp_gain((fighters - [self.winner]).first) if xp_gain.nil?
    winner.update!(xp: winner.xp + xp_gain)
  end

  # Validate that +fighter_a+ & +fighter_b+ are two different Fighters
  # @return [Boolean]
  #
  def has_two_different_opponents?
    if fighter_a == fighter_b
      error_label = I18n.t('activerecord.errors.models.fight.fighter_a.opponents_must_be_differents')
      errors.add(:fighter_a, error_label)
      errors.add(:fighter_b, error_label)
      return false
    end
    return true
  end

  def set_title
    self.title = self.to_s
  end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  before_action :set_fight, only: [:show]

  # GET /fights
  def index
    @pagy, @fights = pagy(Fight.all)
  end

  # GET /fights/1
  def show
  end

  # GET /fights/new
  def new
    @fight = Fight.new
  end

  # POST /fights
  def create
    @fight = Fight.new(fight_params)

    respond_to do |format|
      if @fight.save
        format.html {
          redirect_to [@fight],
          notice: t(
            'shared.notice.successful_creation',
            klass: Fight.model_name.human.humanize,
            instance: @fight
          )
        }
      else
        format.html { render :new }
      end
    end
  end

  private
    def set_fight
      @fight = Fight.find(params[:id])
    end

    def fight_attrs
      [
        :fighter_a_id,
        :fighter_b_id,
      ]
    end

    def fight_params
      params.require(:fight).permit(fight_attrs)
    end

end

app/views/fights/_fields.html.haml
.row
  .col-12.col-sm-6
    .form-group
      = form.association :fighter_a, collection: Fighter.all, include_blank: false

  .col-12.col-sm-6
    .form-group
      = form.association :fighter_b, collection: Fighter.all, include_blank: false

app/views/fights/_form.html.haml
.card.col-12
  .card-body
    = simple_form_for([fight]) do |f|
      = render 'fields', form: f

      .row
        .col-12.text-center
          = f.button :submit, t('shared.action.save'), class: 'btn btn-success'

app/views/fights/_list.html.haml
- title = local_assigns[:title] ? title : Fight.model_name.human.pluralize.humanize

.card

  .card-header
    %h2= title

  .card-body
    .row

      .col-12
        .table-responsive-sm

          %table.table.table-hover.table-sm.align-middle
            %thead.thead-dark.text-center
              %tr
                %th{ scope: 'col' }= t('activerecord.attributes.fight.id').humanize
                %th{ scope: 'col' }= t('activerecord.attributes.fight.title').humanize
                %th{ scope: 'col' }= t('activerecord.attributes.fight.created_at').humanize
                %th
                  - unless local_assigns[:hide_new]
                    = link_to new_fight_path, class: 'btn btn-success' do
                      %i.fas.fa-fw.fa-plus

            %tbody
              - fights.each do |fight|
                %tr
                  %th.text-center{ scope: 'row' }= fight.id
                  %td= fight.title
                  %td= fight.created_at
                  %td.text-center
                    = link_to fight_path(fight), class: 'btn btn-sm btn-info', title: t('shared.action.show') do
                      %i.fas.fa-fw.fa-eye

      - if local_assigns[:pagy]
        .col-12.justify-content-center!= pagy_bootstrap_nav(pagy)

app/views/fights/index.html.haml
= render 'list', fights: @fights, pagy: @pagy

app/views/fights/new.html.haml
= render 'form', fight: @fight

app/views/fights/show.html.haml
.card
  .card-header
    %h2= @fight

  .card-body
    .row
      - fighter_a_class = @fight.winner_id == @fight.fighter_a_id ? 'success' : 'danger'
      - fighter_b_class = @fight.winner_id == @fight.fighter_b_id ? 'success' : 'danger'

      .col-12.col-sm-6.text-center
        = link_to fighter_path(@fight.fighter_a), class: "btn btn-#{fighter_a_class}" do
          %i.fas.fa-fist-raised
          = @fight.fighter_a
      .col-12.col-sm-6.text-center
        = link_to fighter_path(@fight.fighter_b), class: "btn btn-#{fighter_b_class}" do
          %i.fas.fa-fist-raised
          = @fight.fighter_b

    .row
      .col-12
        %hr

    .row
      .col-12.col-sm-6
        %ul.list-group
          - %w(id fighter_a fighter_b winner xp_gain created_at).each do |attribute|
            %li.list-group-item
              %h6= t("activerecord.attributes.fight.#{attribute}").humanize
              %span= @fight.send(attribute)